# Schema for the configuration files of the CustomOlivero theme.
customolivero.settings:
  type: theme_settings
  label: 'CustomOlivero settings'
  mapping:
    example:
      type: string
      label: Example
